language: python
python:
  - "3.5"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls coverage"

script: python -m unittest test/*.py

after_success:
  - coverage run
  - coveralls
