language: python
python:
  - "3.5"

install:
  - "pip install -e ."
  - "pip install -r test_requirements.txt"

script: py.test test --cov=gather --cov=lib --cov-report term-missing

after_success:
  - coveralls
